### ISSUE TITLE
specific.html info alignment issue

### ISSUE THREAD

**Issue by pretzL** [Anclagen/Semester-Project-2#62]
At any resolution, the specific.html page information section has an alignment issue on several elements, see attached screenshot. Some items are centered, others are justified space-between/space-evenly. Perhaps a more uniform approach would be ideal?

![image](https://user-images.githubusercontent.com/30121693/206449503-5eece689-8d05-4a81-9e0f-c17666455a8c.png)

**Comment by Anclagen** [comment]
Converted to table so bidder amount and placed all line up with each other, buttons to be adjusted with skeleton loading
