### ISSUE TITLE
"Update Avatar" modal closes even if I submit a bad value

### ISSUE THREAD

**Issue by pretzL** [Anclagen/Semester-Project-2#65]
If you try submitting a bad image value, for example "test", the modal will still close when you click "submit", eventhough the API request doesn't fire. This in turn makes it so the error message has no chance to display to the user, showing them what they did wrong.

**Comment by Anclagen** [comment]
Removed dismiss modal data attribute on submit button, added error reporting/failed to update message, added a preview of the avatar updates as typed/pasted, submit now awaits ok response and closes form on success, updating profile page avatar.
